# Generated by Django 2.1.7 on 2019-03-11 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='story',
            name='id',
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(db_column='realname', default=None, on_delete=django.db.models.deletion.CASCADE, to='news.Author'),
        ),
        migrations.AlterField(
            model_name='story',
            name='key',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.ForeignKey(db_column='username', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
