# Generated by Django 2.1.7 on 2019-03-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190311_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
