# Generated by Django 2.1.7 on 2019-03-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190311_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(db_column='name', default=None, on_delete=django.db.models.deletion.CASCADE, to='news.Author'),
        ),
    ]
