# Generated by Django 2.1.7 on 2019-03-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190311_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('pol', 'politics'), ('art', 'art'), ('tech', 'technology'), ('trivia', 'trivial')], max_length=64),
        ),
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='story',
            name='region',
            field=models.CharField(choices=[('uk', 'uk'), ('eu', 'European'), ('w', 'world')], max_length=64),
        ),
    ]
