# Generated by Django 2.1.7 on 2019-03-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20190311_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
